apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-python-sample-6raa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rarnaud-tenant/rhtap-python-sample/rhtap-python-sample-6raa@sha256:f109b78e2cb5882152824570a6ef0db8515b991595d8bde2e5c755c811fd1607
        name: container-image
        resources: {}
status: {}
